### ISSUE TITLE
My Firewall is blocking mcpi

### ISSUE THREAD

**Issue by CedRiC-Maker** [martinohanlon/mcpi#23]
Hello Martin,
My name is cedric and I want to teach python for a beginner group.
I ve heard of your work and I may try to include the mcpi lib in my lessons.
But i have a little problem:
I use the windows edition of minecraft (v 1.17)  and i use bedrock server too. I managed to launch a server. Indeed, I think it will be more funny  if anyone can share its work with the others students.

My question is, when I launch a py file with mcpi, i have permission error (in python). I read in the internet that it means my firewall block the transmission. I don't know what to do...
Can you help me please?

Best regards,
Ced

**Comment by CedRiC-Maker** [comment]
Hello,
Today I managed to run the server on a distant computer and i used this code:


> import mcpi.minecraft as minecraft
mc = minecraft.Minecraft.create("IpOfMyServer",4711)
mc.postToChat("hello")
pos = mc.player.getTilePos()
print(pos.x)

 And I got a timeout error! I tried with the 25565 port and 4711 port but nothing works.

`

**Comment by martinohanlon** [comment]
Hi, 

The reason your Python code isnt able to connect is because you need an API or plugin to connect to. The plugin acts as a bridge between Python and Minecraft.

In Minecraft: Pi Edition the API is part of Minecraft.

For Minecraft: Java edition edition you can use a server plus the [RaspberryJuice plugin](https://www.spigotmc.org/resources/raspberryjuice.22724). This is the approach taken in Adventures in Minecraft.  There are [starter kits available from the 2nd edition of Adventures in Minecraft](https://adventuresinminecraft.github.io/) (which I dont think was ever translated into French) and Minecraft v1.12.

I am not aware of a solution for Minecraft: Bed rock edition. There have been similar mods in the past for Minecraft: Pocket edition but I dont think they have been maintained and would now work. (see https://github.com/arpruss/raspberryjam-pe).

Sorry I cant be of more help.

Martin

**Comment by CedRiC-Maker** [comment]
Everything works fine now, I didn't install the API in my server.

My first mistake was to use minecraft Windows edition instead of java edition. 
Berd rock suits to the Windows version but not spigot. I think there is no way to use mcpi with windows edition. Don t you?


Thank for your help.

**Comment by xboxone08** [comment]
I believe the issue is resolved and can be closed?
