### ISSUE TITLE
usage with 1.20.6

### ISSUE THREAD

**Issue by mncrftfrcnm** [martinohanlon/mcpi#37]
How can i port/use it with mc java server on  1.20.6?

**Comment by Bigjango13** [comment]
This is the Python API, it doesn't directly interact with Minecraft Java Edition, instead you need a Minecraft Java mod that supports that version (which is tricky in newer version due to numerical ids no longer existing). As far as I know, such a mod doesn't exist, but for older versions there is:
- https://github.com/zhuowei/RaspberryJuice
- https://github.com/arpruss/raspberryjammod

**Comment by mncrftfrcnm** [comment]
Thank you very much very much for your answer
